apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-1
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/navi63/test-argo.git
      revision: HEAD
      directories:
      - path: argo/git-generator-directory/projects/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/navi63/test-argo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true