apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-alpha
  namespace: argocd
spec:
  description: Project Alpha - E-commerce Platform
  sourceRepos:
    - '*'
  destinations:
    - namespace: project-alpha
      server: https://kubernetes.default.svc