apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project-alpha
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP